use_frameworks!

target 'TDFAlertHelper_Example' do
  pod 'TDFAlertHelper', :path => '../'

  target 'TDFAlertHelper_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
